# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a058821b9e149ca433877fc6cb19d0b33338895ca9dc2afe3a76b1c6a8b73a3de007bc13f557719c824319869c0ce6069bec291b685cc628cf80a6b230181575

test:
  secret_key_base: 0516daf2eae1f78df4add476b2e91a4433bab090f4c9f8877ec6afecfdb2485bbcf9fa878d935f15f137a2e824ea4a08ae280eb0389064f3fca5f8055cd71f65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
